### ISSUE TITLE
강의 자동 스킵 기능 및 일부 버그 수정

### ISSUE THREAD

**Issue by leestana01** [daehyuh/InflearnAutoSkip#1]
다음의 기능을 추가 고려해야합니다.

## 자동 스킵
- 동영상을 자동으로 끝으로 이동
- 매크로로 인한 트래픽 부하 방지를 위해 딜레이 2초로 연장

## 버그 수정
- 강의 화면 외에서 querySelector가 참조하는 값이 없어도 attribute를 클릭하려는 문제 발생
  - 선택자가 참조하는 값이 존재하는지 확인 필요
- 마지막 최종 강의 유무 판단 필요 (최종 강의에서 무한 루프 현상 발생)

**Comment by daehyuh** [comment]
1. 자동스킵 기능 추가
2. 버그 수정
PR Merge 완료

감사합니다
